### ISSUE TITLE
Bug with OS version code

### ISSUE THREAD

**Issue by libertymatters** [laurentpertois/BigSur-Compatibility-Checker#5]
Hello,

While testing out your script I found it doesn't take into account Apple's change during the beta builds of reporting 10.16.x to 11.x.x for Big Sur.  It also uses -buildVersion flag instead of the -productVersion flag for sw_vers.  The end result is a machine can report false for compatibility for upgrade when it is compatible. 

Best,

Joshua Byers

**Comment by laurentpertois** [comment]
Hi @libertymatters,

Thanks for your feedback, I also wish you a happy new year! 

I'd be interested to know which issues you have faced with the actual script? I have switched to using build version instead of product version to avoid issues with Apple changes and also, in other scripts, make the check easier. Build versions are still increasing (for example Mojave is 18, Catalina 19 and Big Sur 20). Using the Product version requires to check more things to adapt what part of the result you want to use. Until Catalina, you would skip the first segment (10.) to focus on the second one (like 15). But starting with Big Sur, you have to check because first if the first segment is 10 or 11 and then adapt to choose what you want to keep. Using the build version, it's easier as the first 2 digits are what you're interested in.

But if you can provide a case where using the Build is providing a False where a True would be expected, I'm highly interested.

If you have unexpected results, could they be related to another part of the script. The hardware model check is usually one that is more tricky.

Thanks again for your feedback and have a nice day.

**Comment by laurentpertois** [comment]
Hello @libertymatters 

Can I close this issue or do you have extra details to provide?

Thanks in advance,
