### ISSUE TITLE
MacBookAir5,1 evals as True

### ISSUE THREAD

**Issue by staze** [laurentpertois/BigSur-Compatibility-Checker#9]
Not sure why. Logic looks okay. But MacBookAir5,1 evals as "True" for Big Sur compatibility when running 10.13.6.

**Comment by staze** [comment]
the line 

"MODELVERSION=$(echo "$MODELIDENTIFIER" | sed -e 's/[^0-9,]//g' -e 's/,//')"

is evaluating as 51, not 5. so maybe the check needs to be adjusted to "-ge 60" rather than "-ge 6"?

**Comment by staze** [comment]
looks like making that change works. 

Or we can change to use awk like other version of compatibility checker:

MODELVERSION=$(echo "$MODELIDENTIFIER" | sed 's/[^0-9,]//g' | awk -F, '{print $1}')

Thoughts?

**Comment by staze** [comment]
changing to awk doesn't quite work for the iMac check (14,4, not just all of 14). 

*sigh* 

yeah, guess need to change to double digits. =(

**Comment by laurentpertois** [comment]
Hi @staze,

Thanks for pointing it to me. You're 100% right, we need to switch to double digits which I decided to do first because of the iMac. The first model that is compatible with Big Sur is the iMac Mid 2014 that has iMac14,4 as identifier. And just using the digits before the comma didn't work for that as it would catch also the iMac Late 2013 (iMac14,1 to 14,3).

Now the thing is that at first I didn't understand because I looked on my own Jamf Pro server that I used for testing and it has a version with double digits for all models but I just realised the one on Github does not. I am deeply sorry for that and very much thankful for your comment.

I'm sending a new version to check correctly on all models using double digits in a few minutes.

Let me know how it goes for you.

Have a nice day

**Comment by staze** [comment]
No worries, thanks for the quick response! yeah, I was super confused as well since I was looking at jamf and it said "True" then Big Sur refused to install on the machine. 

And yes, stupid apple and the 14,4 vs 14,x difference. =(

**Comment by laurentpertois** [comment]
Oh well, I guess those who come with model identifier don't care about our needs in the end :D 

It is now published

**Comment by staze** [comment]
Thank you sir! 

Just updated my system. Looks like identical changes to what I made. =)

Have a great day/evening!
